id: A53CFC341
title: Dharmakāya Transference
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:04:13.333359
  last_modified_at: 2022-03-01 01:04:13.333366
