id: A53CFC341
title: The Sovereign of Confessions for all Impairments and Breakages, Extracted from
  the Rampant Elephant Tantra
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:04:13.335347
  last_modified_at: 2022-03-01 01:04:13.335351
